worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 512; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    server_tokens off;
    sendfile on;
    gzip off;
    client_body_temp_path /tmp/nginx-client;
    fastcgi_temp_path /tmp/nginx-fastcgi;
    proxy_temp_path /tmp/nginx-proxy;
    uwsgi_temp_path /tmp/nginx-uwsgi;
    scgi_temp_path /tmp/nginx-scgi;
    map $uri $unity_encoding {
        default '';
        ~\.(wasm|js|data|symbols\.json)\.br$ br;
        ~\.(wasm|js|data|symbols\.json)\.gz$ gzip;
    }
    map $http_x_forwarded_proto $fastcgi_https { default off; https on; }
    server {
        listen 8080;
        server_name _;
        root /workspace/public;
        index index.php index.html;
        client_max_body_size 20m;
        include /opt/lunar/headers.conf;
        location ~ /\. { deny all; }
        location ~* \.(env|ini|log|sql|sqlite|bak|cgp)$ { deny all; }
        location / { try_files $uri $uri/ =404; }
        location ~ \.php$ {
            try_files $uri =404;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS $fastcgi_https;
            fastcgi_param HTTP_PROXY '';
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_read_timeout 65s;
            include /opt/lunar/headers.conf;
            add_header Cache-Control 'no-store' always;
        }
        location ~ \.(html|htm)$ {
            try_files $uri =404;
            include /opt/lunar/headers.conf;
            add_header Cache-Control 'no-cache' always;
        }
        location ~ \.wasm(\.gz|\.br)?$ { types {} default_type application/wasm; try_files $uri =404; expires 1h; }
        location ~ \.js(\.gz|\.br)$ { types {} default_type application/javascript; try_files $uri =404; expires 1h; }
        location ~ \.(data|symbols\.json)\.gz$ { types {} default_type application/gzip; try_files $uri =404; expires 1h; }
        location ~ \.(data|symbols\.json)\.br$ { types {} default_type application/octet-stream; try_files $uri =404; expires 1h; }
        location ~ \.(data|unityweb)$ { types {} default_type application/octet-stream; try_files $uri =404; expires 1h; }
    }
}
