[global]
pid = /tmp/php-fpm.pid
error_log = /proc/self/fd/2
daemonize = no
[www]
listen = 127.0.0.1:9000
pm = ondemand
pm.max_children = 3
pm.process_idle_timeout = 10s
pm.max_requests = 300
clear_env = yes
catch_workers_output = yes
request_terminate_timeout = 60s
security.limit_extensions = .php
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /proc/self/fd/2
