CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL,
 role TEXT NOT NULL CHECK(role IN ('admin','user')), enabled INTEGER NOT NULL DEFAULT 1,
 allowed_ips TEXT NOT NULL DEFAULT '[]', quota INTEGER NOT NULL DEFAULT 10,
 created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS resources (
 id TEXT PRIMARY KEY, owner TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL, name TEXT NOT NULL,
 data TEXT NOT NULL, created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS resources_owner_kind ON resources(owner,kind);
CREATE TABLE IF NOT EXISTS audit (
 id INTEGER PRIMARY KEY AUTOINCREMENT, actor TEXT NOT NULL, action TEXT NOT NULL,
 target TEXT NOT NULL, created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS jobs (
 id TEXT PRIMARY KEY, owner TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL,
 target TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'queued',
 result TEXT NOT NULL DEFAULT '{}', error TEXT NOT NULL DEFAULT '',
 created INTEGER NOT NULL, started INTEGER, finished INTEGER
);
CREATE INDEX IF NOT EXISTS jobs_owner_created ON jobs(owner,created);
CREATE TABLE IF NOT EXISTS monitor_settings (
 domain_id TEXT PRIMARY KEY REFERENCES resources(id) ON DELETE CASCADE,
 owner TEXT NOT NULL REFERENCES users(id), enabled INTEGER NOT NULL DEFAULT 0,
 config TEXT NOT NULL DEFAULT '{}', next_check INTEGER NOT NULL DEFAULT 0,
 state TEXT NOT NULL DEFAULT 'unknown', failures INTEGER NOT NULL DEFAULT 0,
 analytics_key TEXT NOT NULL, salt TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS monitor_checks (
 id INTEGER PRIMARY KEY AUTOINCREMENT, domain_id TEXT NOT NULL, checked INTEGER NOT NULL,
 status INTEGER NOT NULL, latency_ms INTEGER NOT NULL, error TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS monitor_checks_domain_time ON monitor_checks(domain_id,checked);
CREATE TABLE IF NOT EXISTS analytics_events (
 id INTEGER PRIMARY KEY AUTOINCREMENT, domain_id TEXT NOT NULL, day TEXT NOT NULL,
 at INTEGER NOT NULL, visitor TEXT NOT NULL, path TEXT NOT NULL, kind TEXT NOT NULL,
 referrer TEXT NOT NULL DEFAULT '', x INTEGER NOT NULL DEFAULT 0, y INTEGER NOT NULL DEFAULT 0,
 viewport TEXT NOT NULL DEFAULT 'desktop', target TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS analytics_domain_day ON analytics_events(domain_id,day);
CREATE TABLE IF NOT EXISTS backup_plans (
 id TEXT PRIMARY KEY, owner TEXT NOT NULL REFERENCES users(id), app_id TEXT NOT NULL,
 config TEXT NOT NULL, next_run INTEGER NOT NULL, enabled INTEGER NOT NULL DEFAULT 1,
 last_job TEXT NOT NULL DEFAULT ''
);
