export function mailPanel({api,esc,modal,input,select,getMe,toast}) {
  const $=q=>document.querySelector(q);
  const button='rounded-xl border border-white/80 bg-white/70 px-4 py-2.5 text-xs shadow-sm transition hover:bg-mint/30';
  async function render(){
    const data=await api('/v5/mail');const admin=getMe().role==='admin';
    $('#content').innerHTML=`<section class="mb-5 rounded-2xl border border-white/80 bg-white/75 p-6"><div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-lg font-semibold">Mail hosting</h2><p class="mt-2 text-sm text-slate-500">${esc(data.settings.hostname||'The administrator has not configured a mail hostname yet.')}</p></div>${admin?`<button id="mail-server" class="${button}">Server configuration</button>`:''}</div><div class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-mint/25 p-4 text-sm">IMAP · TLS port 993</div><div class="rounded-xl bg-mint/25 p-4 text-sm">SMTP · STARTTLS port 587</div><div class="rounded-xl bg-mint/25 p-4 text-sm">SMTP · TLS port 465</div></div><p class="mt-4 text-xs leading-6 text-slate-500">Sign in using your complete email address and mailbox password. Public mail ports are ${data.settings.enabled?'enabled':'disabled'}. A trusted certificate, DNS records, provider reverse DNS, and an unrestricted SMTP connection are required for public delivery. Mailbox quotas are separate from application workspace allocations.</p></section><div class="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold">Mailboxes</h2><button id="mail-create" class="rounded-xl bg-forest px-4 py-2.5 text-xs text-white">Create mailbox</button></div><div class="mb-8 grid gap-4 lg:grid-cols-2">${data.mailboxes.map(m=>`<section class="rounded-2xl border border-white/80 bg-white/75 p-5"><h3 class="break-all font-semibold">${esc(m.address)}</h3><p class="my-3 text-xs text-slate-500">${m.enabled?'Enabled':'Disabled'} · ${m.quota_mb} MiB mailbox quota</p><button data-mailbox="${esc(m.id)}" class="${button}">Manage password & quota</button></section>`).join('')||'<p class="text-sm text-slate-500">Enable mail for a domain below, then create its first mailbox.</p>'}</div><h2 class="mb-4 font-semibold">Domains & DNS setup</h2><div class="grid gap-5">${data.domains.map(d=>`<section class="rounded-2xl border border-white/80 bg-white/75 p-6"><div class="flex flex-wrap items-center justify-between gap-3"><h3 class="font-semibold">${esc(d.name)}</h3><button class="${button}" data-mail-domain="${esc(d.id)}">${d.enabled?'Disable domain mail':'Enable domain mail'}</button></div><p class="my-4 text-xs leading-6 text-slate-500">Create the mail hostname's A record as DNS-only, pointing to ${esc(data.server_ip)}. Keep the website's CDN proxy separate. Ask your provider to set the server's PTR record to ${esc(data.settings.hostname||'your mail hostname')}.</p><pre class="overflow-x-auto rounded-xl bg-forest p-4 text-xs leading-6 text-mint">${esc(`${d.name}. MX 10 ${data.settings.hostname||'mail.example.com'}.
${d.name}. TXT "v=spf1 mx -all"
_dmarc.${d.name}. TXT "v=DMARC1; p=none"
${d.dkim||'Enable domain mail to generate its DKIM signing key.'}`)}</pre><p class="mt-3 text-xs text-slate-500">Merge SPF with any existing senders; only one SPF record is allowed. Start DMARC in monitoring mode, then tighten its policy after checking legitimate mail.</p></section>`).join('')}</div>`;
    if(admin)$('#mail-server').onclick=()=>{modal('Mail server configuration',input('hostname','Mail hostname','text','Use a DNS-only hostname for this VPS.',data.settings.hostname)+select('certificate_domain','Certificate',[['','Development self-signed certificate'],...data.domains.map(d=>[d.id,d.name])],'Issue its certificate in Certificates & CDN first.')+`<label class="flex gap-3"><input type="checkbox" name="enabled" ${data.settings.enabled?'checked':''}> Enable public mail ports</label>`,'Save server settings',async v=>{await api('/v5/mail/server','POST',{...v,enabled:!!v.enabled});$('#dialog').close();toast('Mail server configured');await render()});$('#dialog-fields [name=certificate_domain]').value=data.settings.certificate_domain||'';};
    const edit=box=>{
      const domains=data.domains.filter(d=>d.enabled);if(!domains.length){toast('Enable mail for a domain first.');return}
      const options=box?[domains.find(d=>d.id===box.domain_id),...domains.filter(d=>d.id!==box.domain_id)].filter(Boolean):domains;
      modal(box?'Manage mailbox':'Create mailbox',select('domain_id','Domain',options.map(d=>[d.id,d.name]))+input('local','Mailbox name','text','For example: hello or support.',box?.address.split('@')[0]||'')+input('password',box?'New password (blank keeps current)':'Mailbox password','password','At least 14 characters.').replace(box?' required':'__unused__','')+input('quota_mb','Mailbox quota (MiB)','number','Mail delivery stops when this quota is full.',box?.quota_mb||512)+`<label class="flex gap-3"><input type="checkbox" name="enabled" ${!box||box.enabled?'checked':''}> Enable mailbox</label>`,'Save mailbox',async v=>{await api('/v5/mail/mailboxes','POST',{...v,id:box?.id||'',quota_mb:Number(v.quota_mb),enabled:!!v.enabled});$('#dialog').close();toast('Mailbox saved');await render()});
    };
    $('#mail-create').onclick=()=>edit(null);
    document.querySelectorAll('[data-mailbox]').forEach(b=>b.onclick=()=>edit(data.mailboxes.find(m=>m.id===b.dataset.mailbox)));
    document.querySelectorAll('[data-mail-domain]').forEach(b=>b.onclick=async()=>{const d=data.domains.find(d=>d.id===b.dataset.mailDomain);try{await api('/v5/mail/domains/'+d.id,'POST',{enabled:!d.enabled});await render()}catch(e){toast(e.message)}});
  }
  return {render};
}
