export function workspaceTools({api,esc,glyph,toast,getCurrent,getMe}) {
  const $=s=>document.querySelector(s), content=()=>$('#content');
  const btn=(label,action,primary=false)=>`<button type="button" data-fm="${action}" class="inline-flex items-center justify-center gap-2 rounded-lg border px-3 py-2 text-xs font-medium transition motion-reduce:transition-none disabled:opacity-40 ${primary?'border-emerald-800 bg-forest text-white hover:bg-emerald-900':'border-slate-200 bg-white text-slate-600 hover:border-emerald-300 hover:bg-emerald-50'}">${label}</button>`;
  const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':n<1073741824?(n/1048576).toFixed(1)+' MB':(n/1073741824).toFixed(2)+' GB';
  const date=n=>new Date(n*1000).toLocaleString();
  let apps=[],app='',path='',offset=0,entries=[],selected=new Set(),clipboard=null,editor=null,busy=false,cancel=false;
  const join=(a,b)=>a?a+'/'+b:b;
  const request=(operation,extra={})=>api('/v4/files/'+app,'POST',{operation,path,...extra});
  const safe=fn=>async event=>{try{await fn(event)}catch(error){toast(error.message)}};
  function picker(){return `<select id="fm-app" aria-label="Application workspace" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-xs font-medium text-slate-700">${apps.map(a=>`<option value="${a.id}" ${a.id===app?'selected':''}>${esc(a.name)} · ${esc(a.data.runtime)}</option>`).join('')}</select>`}
  async function init(){apps=await api('/resources/apps');if(!apps.some(a=>a.id===app)){app=apps[0]?.id||'';path='';}return !!app}
  function discard(){return !editor || !editor.dirty || window.confirm('Discard the unsaved changes in '+editor.path+'?')}
  async function navigate(next){if(busy)return;if(!discard())return;editor=null;path=next;offset=0;selected.clear();await list()}
  async function list(){
    if(getCurrent()!=='files')return;
    const requestedApp=app, requestedPath=path;
    const result=await request('list',{offset});if(getCurrent()!=='files'||app!==requestedApp||path!==requestedPath)return;entries=result.entries;selected.clear();
    const roots=path?await request('list',{path:'',offset:0}):result;
    if(getCurrent()!=='files'||app!==requestedApp||path!==requestedPath)return;
    const hidden=sessionStorage.getItem('cgpanel-show-hidden')==='yes';
    const items=entries.filter(e=>hidden||!e.name.startsWith('.'));
    const crumbs=path.split('/').filter(Boolean);
    content().innerHTML=`<section id="fm-shell" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs motion-safe:animate-enter">
      <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 bg-slate-50/70 px-5 py-4"><div class="flex items-center gap-3"><span class="flex size-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-800">${glyph('folder-code','size-5')}</span><div><h2 class="text-sm font-semibold">Files & folders</h2><p class="mt-1 text-[11px] text-slate-400">Your application workspace</p></div></div><div class="flex flex-wrap gap-2">${btn(glyph('plus','size-3.5')+' New file','new-file')}${btn('New folder','new-folder')}${btn('↑ Upload files','upload',true)}<input type="file" id="fm-upload" multiple hidden></div></div>
      <div class="grid lg:grid-cols-[220px_minmax(0,1fr)]"><aside class="border-b border-slate-100 bg-slate-50/50 p-4 lg:border-b-0 lg:border-r">${picker()}<p class="mb-3 mt-6 text-[9px] font-semibold tracking-widest text-slate-400">FOLDERS</p><button data-folder="" class="mb-1 flex w-full items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2.5 text-left text-xs font-medium text-emerald-800">${glyph('folder-code','size-4')} Workspace</button><div class="max-h-64 overflow-auto lg:max-h-[520px]">${roots.entries.filter(e=>e.kind==='directory'&&(hidden||!e.name.startsWith('.'))).map(e=>`<button data-folder="${esc(e.name)}" class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs text-slate-500 hover:bg-slate-100">${glyph('folder-code','size-4')}<span class="truncate">${esc(e.name)}</span></button>`).join('')}</div><button data-folder=".cgpanel-trash" class="mt-6 text-xs text-slate-400 hover:text-slate-700">Trash</button><p class="mt-2 text-[10px] leading-5 text-slate-400">Deleted items go to Trash. Move them back to restore.</p></aside>
      <div class="min-w-0"><div class="flex flex-wrap items-center gap-2 border-b border-slate-100 px-4 py-3"><button data-folder="${esc(crumbs.slice(0,-1).join('/'))}" aria-label="Parent folder" class="rounded-lg border border-slate-200 px-2.5 py-1.5 text-slate-500">↑</button><nav aria-label="Folder breadcrumb" class="flex flex-1 flex-wrap items-center gap-2 text-xs"><button data-folder="" class="text-emerald-700">Workspace</button>${crumbs.map((p,i)=>`<span class="text-slate-300">/</span><button data-folder="${esc(crumbs.slice(0,i+1).join('/'))}" class="max-w-48 truncate text-slate-600">${esc(p)}</button>`).join('')}</nav>${btn('↻','refresh')}</div>
      <div class="flex flex-wrap items-center gap-2 border-b border-slate-100 px-4 py-3">${['Edit','Download','Rename','Copy','Move','Paste','Compress','Extract','Permissions','Trash'].map(x=>btn(x,x.toLowerCase())).join('')}<span id="fm-selection" class="ml-auto text-[11px] text-slate-400">Select a file or folder</span></div>
      <div class="flex flex-wrap items-center gap-3 border-b border-slate-100 px-4 py-3"><input id="fm-search" aria-label="Filter files" placeholder="Filter visible files…" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-xs"><label class="flex items-center gap-2 text-[11px] text-slate-500"><input id="fm-hidden" type="checkbox" ${hidden?'checked':''} class="accent-emerald-700"> Hidden files</label></div>
      <div class="min-h-80 overflow-auto lg:max-h-[560px]"><table class="w-full text-left text-xs"><thead class="sticky top-0 bg-slate-50 text-[10px] text-slate-400"><tr><th class="w-10 px-4 py-3"><input id="fm-all" type="checkbox" aria-label="Select all visible files" class="accent-emerald-700"></th><th class="px-3 py-3 font-medium">Name</th><th class="px-3 py-3 font-medium">Size</th><th class="hidden px-3 py-3 font-medium md:table-cell">Modified</th><th class="hidden px-3 py-3 font-medium xl:table-cell">Permissions</th></tr></thead><tbody id="fm-rows">${items.map((e)=>`<tr data-entry="${esc(e.name)}" class="group border-t border-slate-100 hover:bg-emerald-50/40 [&.selected]:bg-emerald-50"><td class="px-4 py-3"><input data-check="${esc(e.name)}" type="checkbox" aria-label="Select ${esc(e.name)}" class="accent-emerald-700"></td><td class="px-3 py-3"><button data-open="${esc(e.name)}" class="flex max-w-full items-center gap-3 text-left font-medium text-slate-700"><span class="flex size-8 shrink-0 items-center justify-center rounded-lg ${e.kind==='directory'?'bg-amber-50 text-amber-600':'bg-slate-100 text-slate-400'}">${glyph(e.kind==='directory'?'folder-code':'file-text','size-4')}</span><span class="max-w-xs truncate">${esc(e.name)}</span>${e.kind==='link'?'<span class="text-[10px] text-amber-600">Link</span>':''}</button></td><td class="whitespace-nowrap px-3 py-3 text-slate-400">${e.kind==='directory'?'—':size(e.size)}</td><td class="hidden whitespace-nowrap px-3 py-3 text-[11px] text-slate-400 md:table-cell">${date(e.modified)}</td><td class="hidden px-3 py-3 font-mono text-[11px] text-slate-400 xl:table-cell">${esc(e.mode)}</td></tr>`).join('')||'<tr><td colspan="5" class="px-6 py-20 text-center text-slate-400">This folder is empty. Drop files here or choose Upload files.</td></tr>'}</tbody></table></div>
      <div class="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-[11px] text-slate-400"><span>${result.total} items · Drop files anywhere to upload</span><div class="flex gap-2">${offset?btn('Previous','previous'):''}${offset+400<result.total?btn('Next','next'):''}</div></div></div></div>
      <div id="fm-progress" class="border-t border-emerald-100 bg-emerald-50 px-5 py-4" hidden><div class="flex justify-between text-xs text-emerald-800"><span id="fm-progress-text"></span><button id="fm-cancel" class="font-medium">Cancel</button></div><progress id="fm-meter" max="100" value="0" class="mt-3 h-2 w-full accent-emerald-700"></progress></div>
      <div id="fm-editor"></div></section>`;
    document.querySelectorAll('[data-folder]').forEach(el=>el.onclick=safe(()=>navigate(el.dataset.folder)));
    document.querySelectorAll('[data-open]').forEach(el=>el.onclick=safe(()=>open(el.dataset.open)));
    document.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{el.checked?selected.add(el.dataset.check):selected.delete(el.dataset.check);selection()});
    $('#fm-all').onchange=e=>{document.querySelectorAll('[data-entry]').forEach(row=>{if(row.hidden)return;const checkbox=row.querySelector('input');checkbox.checked=e.target.checked;checkbox.onchange()})};
    $('#fm-search').oninput=e=>document.querySelectorAll('[data-entry]').forEach(row=>row.hidden=!row.dataset.entry.toLowerCase().includes(e.target.value.toLowerCase()));
    $('#fm-hidden').onchange=safe(async e=>{sessionStorage.setItem('cgpanel-show-hidden',e.target.checked?'yes':'no');await list()});
    $('#fm-app').onchange=safe(async e=>{if(busy){e.target.value=app;toast('Finish or cancel the transfer first.');return}if(!discard()){e.target.value=app;return}app=e.target.value;path='';offset=0;editor=null;await list()});
    document.querySelectorAll('[data-fm]').forEach(el=>el.onclick=safe(()=>action(el.dataset.fm)));
    $('#fm-upload').onchange=safe(e=>upload([...e.target.files]));
    $('#fm-cancel').onclick=()=>cancel=true;
    $('#fm-shell').ondragover=e=>{e.preventDefault();e.currentTarget.classList.add('ring-2','ring-emerald-300')};
    $('#fm-shell').ondragleave=e=>e.currentTarget.classList.remove('ring-2','ring-emerald-300');
    $('#fm-shell').ondrop=safe(async e=>{e.preventDefault();e.currentTarget.classList.remove('ring-2','ring-emerald-300');await upload([...e.dataTransfer.files])});selection();
  }
  function selection(){const n=selected.size;$('#fm-selection').textContent=n?`${n} selected`:'Select a file or folder';document.querySelectorAll('[data-entry]').forEach(row=>row.classList.toggle('selected',selected.has(row.dataset.entry)));for(const name of ['edit','download','rename','permissions','compress','extract'])document.querySelector(`[data-fm="${name}"]`).disabled=n!==1;for(const name of ['copy','move','trash'])document.querySelector(`[data-fm="${name}"]`).disabled=!n;document.querySelector('[data-fm="paste"]').disabled=!clipboard||clipboard.app!==app;}
  async function action(name){
    if(busy)return;
    const first=[...selected][0];
    if(name==='refresh'){if(discard()){editor=null;await list()}return}
    if(name==='previous'||name==='next'){offset+=name==='next'?400:-400;await list();return}
    if(name==='upload'){$('#fm-upload').click();return}
    if(name==='edit'){await edit(first);return}
    if(name==='download'){await download(first);return}
    if(name==='new-folder'||name==='new-file'){const value=prompt(name==='new-folder'?'Folder name':'File name');if(!value)return;await request(name==='new-folder'?'mkdir':'touch',{path:join(path,value)});await list();if(name==='new-file')await edit(value);return}
    if(name==='copy'||name==='move'){clipboard={app,path,names:[...selected],operation:name};selection();toast(`${selected.size} item(s) ready. Open the destination folder and choose Paste.`);return}
    if(name==='paste'){for(const item of clipboard.names)await request(clipboard.operation,{path:join(clipboard.path,item),destination:join(path,item)});clipboard=null;await list();return}
    if(name==='compress'||name==='extract'){const value=prompt(name==='compress'?'Archive name':'Extract into a new folder',name==='compress'?first+'.zip':first.replace(/\.(zip|cgp)$/i,'')+'_extracted');if(!value)return;await request(name==='compress'?'archive':'extract',{path:join(path,first),destination:join(path,value)});await list();return}
    if(name==='rename'){const value=prompt('New name',first);if(!value||value===first)return;await request('move',{path:join(path,first),destination:join(path,value)});await list();return}
    if(name==='permissions'){const value=prompt('Permissions (for example 644 for files or 755 for folders)',entries.find(e=>e.name===first).mode);if(!value)return;await request('chmod',{path:join(path,first),mode:value});await list();return}
    if(name==='trash'){if(!confirm(`Move ${selected.size} selected item(s) to Trash?`))return;for(const item of selected)await request('trash',{path:join(path,item)});await list()}
  }
  async function open(name){const item=entries.find(e=>e.name===name);if(item.kind==='directory')await navigate(join(path,name));else if(item.kind==='file')await edit(name);else toast('Symbolic links and special files cannot be opened.')}
  async function edit(name){if(!discard())return;const item=entries.find(e=>e.name===name);if(item?.kind!=='file')throw new Error('Choose a regular text file to edit.');const file=join(path,name);const data=await request('read',{path:file});editor={path:file,revision:data.revision,dirty:false};
    $('#fm-editor').innerHTML=`<section class="border-t border-slate-200"><header class="flex flex-wrap items-center justify-between gap-3 bg-slate-900 px-5 py-3 text-white"><div class="flex min-w-0 items-center gap-3 text-xs"><span class="rounded bg-white/10 px-2 py-1 font-mono">${esc(name.split('.').pop()?.toUpperCase()||'TEXT')}</span><span class="truncate">${esc(file)}</span><span id="fm-dirty" class="text-amber-300"></span></div><div class="flex gap-2">${btn('Close','close-editor')}${btn('Save changes · Ctrl+S','save-editor',true)}</div></header><div class="flex flex-wrap gap-2 border-b border-slate-200 bg-slate-50 px-4 py-2"><input id="fm-find" placeholder="Find in file" aria-label="Find in file" class="rounded border border-slate-200 px-3 py-1.5 text-xs"><input id="fm-replace" placeholder="Replace with" aria-label="Replacement text" class="rounded border border-slate-200 px-3 py-1.5 text-xs">${btn('Find next','find')}${btn('Replace all','replace')}</div><div class="flex bg-[#10241e]"><pre id="fm-lines" aria-hidden="true" class="max-h-[520px] w-14 shrink-0 overflow-hidden border-r border-white/10 py-4 pr-3 text-right font-mono text-xs leading-6 text-slate-500"></pre><textarea id="fm-text" spellcheck="false" aria-label="Code editor" wrap="off" class="h-[520px] min-w-0 flex-1 resize-y border-0 bg-transparent p-4 font-mono text-xs leading-6 text-emerald-50 outline-none"></textarea></div><footer class="flex justify-between bg-slate-50 px-5 py-2 text-[10px] text-slate-400"><span id="fm-cursor"></span><span>UTF-8 · Tab inserts spaces · Ctrl/Cmd+S to save</span></footer></section>`;
    const area=$('#fm-text');area.value=data.content;
    const stats=()=>{$('#fm-lines').textContent=Array.from({length:area.value.split('\n').length},(_,i)=>i+1).join('\n');const before=area.value.slice(0,area.selectionStart).split('\n');$('#fm-cursor').textContent=`Line ${before.length}, column ${before.at(-1).length+1} · ${size(new TextEncoder().encode(area.value).length)}`;$('#fm-dirty').textContent=editor.dirty?'● Unsaved':''};
    area.oninput=()=>{editor.dirty=true;stats()};area.onkeyup=stats;area.onclick=stats;area.onscroll=()=>$('#fm-lines').scrollTop=area.scrollTop;
    area.onkeydown=safe(async e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();await save()}if(e.key==='Tab'){e.preventDefault();area.setRangeText('  ',area.selectionStart,area.selectionEnd,'end');area.oninput()}});
    document.querySelector('[data-fm="save-editor"]').onclick=safe(save);
    document.querySelector('[data-fm="close-editor"]').onclick=()=>{if(discard()){editor=null;$('#fm-editor').innerHTML=''}};
    document.querySelector('[data-fm="find"]').onclick=()=>{const query=$('#fm-find').value;if(!query)return;let at=area.value.indexOf(query,area.selectionEnd);if(at<0)at=area.value.indexOf(query);if(at<0){toast('No match found');return}area.focus();area.setSelectionRange(at,at+query.length);stats()};
    document.querySelector('[data-fm="replace"]').onclick=()=>{const query=$('#fm-find').value;if(!query)return;area.value=area.value.split(query).join($('#fm-replace').value);area.oninput()};stats();$('#fm-editor').scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
  }
  async function save(){if(!editor)return;const active=editor,area=$('#fm-text'),value=area.value,button=document.querySelector('[data-fm="save-editor"]');if(button.disabled)return;button.disabled=true;try{const result=await request('save',{path:active.path,content:value,revision:active.revision});active.revision=result.revision;if(editor===active&&getCurrent()==='files'){active.dirty=area.value!==value;$('#fm-dirty').textContent=active.dirty?'● Unsaved':'Saved';toast('Changes saved')}}finally{button.disabled=false}}

  function progress(label,percent){$('#fm-progress').hidden=false;$('#fm-progress-text').textContent=label;$('#fm-meter').value=percent}
  async function upload(files){if(busy||!files.length)return;if(!discard())return;busy=true;cancel=false;try{for(const file of files){if(cancel)break;if(file.size>2*1024**3)throw new Error('The upload limit is 2 GiB per file.');const dest=join(path,file.name);let overwrite=false;if(entries.some(e=>e.name===file.name)){overwrite=confirm(`Replace ${file.name}?`);if(!overwrite)continue}const start=await request('upload_begin',{path:dest});try{for(let at=0;at<file.size;){if(cancel)throw new Error('Upload cancelled');const bytes=new Uint8Array(await file.slice(at,at+196608).arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await request('upload_chunk',{path:dest,upload:start.upload,offset:at,data:btoa(binary)});at=result.next;progress(`Uploading ${file.name} · ${size(at)} / ${size(file.size)}`,at/file.size*100)}await request('upload_finish',{path:dest,upload:start.upload,overwrite})}catch(error){await request('upload_cancel',{path:dest,upload:start.upload}).catch(()=>{});throw error}}toast(cancel?'Upload cancelled':'Upload complete')}finally{busy=false;await list()}}
  async function download(name){const file=entries.find(e=>e.name===name);if(file?.kind!=='file')throw new Error('Choose one file to download.');let writer;if(window.showSaveFilePicker){const handle=await window.showSaveFilePicker({suggestedName:name});writer=await handle.createWritable()}else if(file.size>128*1024**2)throw new Error('For downloads over 128 MB, use Chrome/Edge with file saving enabled or SFTP.');busy=true;cancel=false;const chunks=[];try{let at=0;do{if(cancel)throw new Error('Download cancelled');const result=await request('download',{path:join(path,name),offset:at});const bytes=Uint8Array.from(atob(result.data),c=>c.charCodeAt(0));if(writer)await writer.write(bytes);else chunks.push(bytes);at=result.next;progress(`Downloading ${name} · ${size(at)} / ${size(result.size)}`,result.size?at/result.size*100:100);if(result.done)break}while(true);if(writer)await writer.close();else{const url=URL.createObjectURL(new Blob(chunks));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}toast('Download complete')}catch(error){if(writer)await writer.abort();throw error}finally{busy=false;$('#fm-progress').hidden=true}}
  async function jobs(kind,target,extra){await api('/v2/jobs','POST',{kind,target,...extra});toast('Queued. Follow progress in Background jobs.');location.hash='jobs'}
  async function developerPage(page){if(!await init()){content().innerHTML='<p class="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Create an application first.</p>';return}const catalog=page==='runtimes'?await api('/v4/runtimes'):null;const cards=await Promise.all(apps.map(async a=>{const info=await api(`/v4/${page==='runtimes'?'runtimes':'ide'}/${a.id}`);if(page==='runtimes')return `<section class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="text-sm font-semibold">${esc(a.name)}</h2><p class="mt-2 text-xs text-slate-500">${esc(info.runtime)} · ${esc(info.version||'Existing runtime / custom profile')}</p><p class="mt-2 break-all font-mono text-[10px] text-slate-400">${esc(info.image||'')}</p><form data-runtime="${a.id}" class="mt-5 space-y-3"><label class="block text-xs text-slate-500">Version<select name="version" required class="mt-2 w-full rounded-lg border border-slate-200 p-2.5">${(catalog[info.runtime]||[]).map(v=>`<option ${v===info.version?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label class="block text-xs text-slate-500">Startup command<textarea name="command" rows="2" class="mt-2 w-full rounded-lg border border-slate-200 p-3 font-mono text-xs">${esc(info.command||'')}</textarea></label><button class="rounded-lg bg-forest px-4 py-2.5 text-xs text-white">Apply version</button></form></section>`;
      return `<section class="rounded-xl border border-slate-200 bg-white p-5"><div class="flex items-start justify-between"><div><h2 class="text-sm font-semibold">${esc(a.name)}</h2><p class="mt-2 text-xs text-slate-500">${info.enabled?'code-server is enabled':'Browser IDE is not running'}</p></div><span class="rounded-md bg-slate-100 px-2 py-1 text-[10px] text-slate-500">384 MB limit</span></div><p class="my-5 text-xs leading-6 text-slate-400">VS Code in your browser, with extensions, a terminal, and Git. Your application files are shared with this workspace.</p><div class="flex flex-wrap gap-2">${info.enabled?`<button data-launch="${a.id}" data-url="${esc(info.url)}" class="rounded-lg bg-forest px-4 py-2.5 text-xs text-white">Open IDE</button><button data-ide="${a.id}" data-enabled="false" class="rounded-lg border border-slate-200 px-4 py-2.5 text-xs">Stop IDE</button><button data-rotate="${a.id}" class="text-xs text-slate-400">Reset password</button>`:`<button data-ide="${a.id}" data-enabled="true" class="rounded-lg bg-forest px-4 py-2.5 text-xs text-white">${info.installed?'Start':'Install'} code-server</button>`}</div><div id="ide-secret-${a.id}" class="mt-4" hidden></div></section>`}));
    content().innerHTML=`<p class="mb-5 rounded-xl border border-emerald-100 bg-emerald-50 px-5 py-4 text-xs leading-6 text-emerald-900/70">${page==='runtimes'?'Versions are selected per application. Changing one briefly restarts it and preserves its files and environment. A failed container startup rolls back automatically; test your application before changing production versions. Existing custom runtimes remain unchanged until you select a replacement.':'Install code-server only for workspaces that need it. It uses a separate HTTPS address and password, and runs without host root access. Stop it when you are finished to free memory.'}</p><div class="grid gap-5 lg:grid-cols-2">${cards.join('')}</div>`;
    document.querySelectorAll('[data-runtime]').forEach(form=>form.onsubmit=safe(async e=>{e.preventDefault();if(!confirm('Switch this application runtime? Its files are preserved, but dependencies and your startup command must support the new version.'))return;await jobs('runtime',form.dataset.runtime,Object.fromEntries(new FormData(form)))}));
    document.querySelectorAll('[data-ide]').forEach(button=>button.onclick=safe(()=>jobs('ide',button.dataset.ide,{enabled:button.dataset.enabled==='true'})));
    document.querySelectorAll('[data-rotate]').forEach(button=>button.onclick=safe(()=>jobs('ide',button.dataset.rotate,{enabled:true,rotate:true})));
    document.querySelectorAll('[data-launch]').forEach(button=>button.onclick=safe(async()=>{const result=await api('/v4/ide/'+button.dataset.launch+'/password','POST',{});const area=$('#ide-secret-'+button.dataset.launch);area.hidden=false;area.innerHTML=`<p class="mb-2 text-xs text-slate-500">Use this password on the IDE login screen:</p><input readonly aria-label="IDE password" class="w-full rounded-lg border border-slate-200 p-3 font-mono text-xs" value="${esc(result.password)}"><a href="${esc(button.dataset.url)}" target="_blank" rel="noopener noreferrer" class="mt-3 inline-block text-xs font-medium text-emerald-700">Launch code-server ↗</a>`}));
  }
  async function updates(){const info=await api('/v4/updates');content().innerHTML=`<div class="grid gap-5 lg:grid-cols-2"><section class="rounded-xl border border-slate-200 bg-white p-6"><span class="text-[10px] font-semibold tracking-widest text-emerald-600">RELEASE CHANNEL · STABLE</span><h2 class="mt-3 text-2xl font-semibold">CGPanel ${esc(info.installed)}</h2><p class="mt-3 text-xs leading-6 text-slate-500">Updates come from published stable releases in ItzGlace/CGPanel on GitHub. Each update verifies the bundle checksum, creates a recovery snapshot, and checks the panel after installation.</p><label class="mt-6 flex items-center gap-3 text-sm"><input id="auto-update" type="checkbox" ${info.config.enabled?'checked':''} class="size-4 accent-emerald-700"> Automatically install stable updates</label><p class="mt-2 text-[11px] text-slate-400">Checked every six hours. Panel access pauses briefly during installation.</p><div class="mt-6 flex gap-3">${btn('Check for updates','check')}${btn('Install available update','apply',true)}</div></section><section class="rounded-xl border border-slate-200 bg-white p-6"><h2 class="text-sm font-semibold">Update status</h2><dl class="mt-5 space-y-4 text-xs"><div><dt class="text-slate-400">Status</dt><dd class="mt-1 font-medium">${esc(info.status.state||'Not checked yet')}</dd></div><div><dt class="text-slate-400">Latest release</dt><dd class="mt-1">${esc(info.status.available||'—')}</dd></div><div><dt class="text-slate-400">Last check</dt><dd class="mt-1">${info.status.checked_at?date(info.status.checked_at):'—'}</dd></div></dl>${info.status.error?`<p class="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-700">${esc(info.status.error)}</p>`:''}<a href="https://github.com/ItzGlace/CGPanel/releases" target="_blank" rel="noopener noreferrer" class="mt-6 inline-block text-xs text-emerald-700">Release notes ↗</a></section></div>`;
    $('#auto-update').onchange=safe(async e=>{await api('/v4/updates','POST',{action:'settings',enabled:e.target.checked});toast(e.target.checked?'Automatic updates enabled':'Automatic updates disabled')});
    document.querySelectorAll('[data-fm]').forEach(button=>button.onclick=safe(async()=>{if(button.dataset.fm==='apply'&&!confirm('Install the available stable update? Panel access will briefly restart.'))return;await api('/v4/updates','POST',{action:button.dataset.fm});toast('Update task started. Refresh this page to see its status.')}));
  }
  document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#"]');if(!link||getCurrent()!=='files'||link.hash==='#files')return;if(busy){event.preventDefault();event.stopImmediatePropagation();toast('Finish or cancel the transfer first.')}else if(!discard()){event.preventDefault();event.stopImmediatePropagation()}else editor=null},true);
  window.addEventListener('beforeunload',event=>{if(busy||editor?.dirty){event.preventDefault();event.returnValue=''}});
  return {async render(page){if(page==='updates')return updates();if(page!=='files')return developerPage(page);if(await init())await list();else content().innerHTML='<p class="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Create an application to start managing files.</p>'}};
}
